from llama_index.core import PromptTemplate

CITATION_QA_TEMPLATE = PromptTemplate(
    "Vui lòng cung cấp câu trả lời chỉ dựa trên các nguồn được cung cấp dưới đây. "
    "Khi tham khảo thông tin từ một nguồn, "
    "hãy trích dẫn nguồn phù hợp bằng cách sử dụng số tương ứng của chúng. "
    "Mọi câu trả lời phải bao gồm ít nhất một trích dẫn nguồn. "
    "Chỉ trích dẫn nguồn khi bạn thực sự tham chiếu đến nó. "
    "Nếu không có nguồn nào hữu ích, bạn hãy nói rõ điều đó.\n"
    "Ví dụ:\n"
    "Nguồn 1:\n"
    "Bầu trời đỏ vào buổi tối và xanh vào buổi sáng.\n"
    "Nguồn 2:\n"
    "Nước ướt khi bầu trời đỏ.\n"
    "Câu hỏi: Khi nào nước ướt?\n"
    "Trả lời: Nước sẽ ướt khi bầu trời đỏ [2], "
    "điều này xảy ra vào buổi tối [1].\n"
    "Bây giờ đến lượt bạn. Dưới đây là các nguồn thông tin được đánh số:"
    "\n------\n"
    "{context_str}"
    "\n------\n"
    "Câu hỏi: {query_str}\n"
    "Trả lời: "
)

CITATION_REFINE_TEMPLATE = PromptTemplate(
    "Vui lòng cung cấp câu trả lời chỉ dựa trên các nguồn được cung cấp. "
    "Khi tham khảo thông tin từ một nguồn, "
    "hãy trích dẫn nguồn phù hợp bằng cách sử dụng số tương ứng của chúng. "
    "Mọi câu trả lời phải bao gồm ít nhất một trích dẫn nguồn. "
    "Chỉ trích dẫn nguồn khi bạn thực sự tham chiếu đến nó. "
    "Nếu không có nguồn nào hữu ích, hãy nói rõ điều đó.\n"
    "Ví dụ:\n"
    "Nguồn 1:\n"
    "Bầu trời đỏ vào buổi tối và xanh vào buổi sáng.\n"
    "Nguồn 2:\n"
    "Nước ướt khi bầu trời đỏ.\n"
    "Câu hỏi: Khi nào nước ướt?\n"
    "Trả lời: Nước sẽ ướt khi bầu trời đỏ [2], "
    "điều này xảy ra vào buổi tối [1].\n"
    "Bây giờ đến lượt bạn. "
    "Chúng tôi đã cung cấp một câu trả lời hiện có: {existing_answer}\n"
    "Dưới đây là một số nguồn thông tin được đánh số. "
    "Hãy sử dụng chúng để tinh chỉnh câu trả lời hiện có. "
    "Nếu các nguồn được cung cấp không hữu ích, hãy lặp lại câu trả lời hiện có."
    "\nBắt đầu tinh chỉnh!"
    "\n------\n"
    "{context_msg}"
    "\n------\n"
    "Câu hỏi: {query_str}\n"
    "Trả lời: "
)